/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Daniel Enriquez
 */
public class EditView extends javax.swing.JFrame {

    /**
     * Creates new form EditView
     */
    public EditView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        updatePhoneType = new javax.swing.JComboBox<>();
        jTextField17 = new javax.swing.JTextField();
        botonActualizar = new javax.swing.JButton();
        updateLastName = new javax.swing.JTextField();
        updateName = new javax.swing.JTextField();
        updatePhone = new javax.swing.JTextField();
        updateBirthday = new javax.swing.JTextField();
        updateAdress = new javax.swing.JTextField();
        updateUser = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        phoneType = new javax.swing.JLabel();
        adress = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 196, 196));
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 600));
        jPanel1.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(196, 196, 196));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Editar Usuario");
        jTextField1.setBorder(null);
        jTextField1.setMaximumSize(new java.awt.Dimension(0, 0));
        jTextField1.setMinimumSize(new java.awt.Dimension(0, 0));
        jTextField1.setPreferredSize(new java.awt.Dimension(0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(330, 50, 280, 100);

        updatePhoneType.setBackground(new java.awt.Color(255, 255, 255));
        updatePhoneType.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        updatePhoneType.setForeground(new java.awt.Color(0, 0, 0));
        updatePhoneType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fijo", "movil" }));
        updatePhoneType.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        updatePhoneType.setMaximumSize(new java.awt.Dimension(0, 0));
        updatePhoneType.setMinimumSize(new java.awt.Dimension(0, 0));
        updatePhoneType.setPreferredSize(new java.awt.Dimension(0, 0));
        updatePhoneType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePhoneTypeActionPerformed(evt);
            }
        });
        jPanel1.add(updatePhoneType);
        updatePhoneType.setBounds(720, 230, 180, 40);

        jTextField17.setBackground(new java.awt.Color(196, 196, 196));
        jTextField17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(0, 0, 0));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("Developed by jviedman dev - enriquez dev");
        jTextField17.setBorder(null);
        jPanel1.add(jTextField17);
        jTextField17.setBounds(211, 540, 520, 19);

        botonActualizar.setBackground(new java.awt.Color(131, 131, 131));
        botonActualizar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        botonActualizar.setForeground(new java.awt.Color(0, 0, 0));
        botonActualizar.setText("Actualizar");
        botonActualizar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(botonActualizar);
        botonActualizar.setBounds(400, 460, 170, 60);

        updateLastName.setBackground(new java.awt.Color(255, 255, 255));
        updateLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        updateLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(updateLastName);
        updateLastName.setBounds(280, 320, 180, 40);

        updateName.setBackground(new java.awt.Color(255, 255, 255));
        updateName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        updateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateNameActionPerformed(evt);
            }
        });
        jPanel1.add(updateName);
        updateName.setBounds(280, 260, 180, 40);

        updatePhone.setBackground(new java.awt.Color(255, 255, 255));
        updatePhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        updatePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePhoneActionPerformed(evt);
            }
        });
        jPanel1.add(updatePhone);
        updatePhone.setBounds(720, 300, 180, 40);

        updateBirthday.setBackground(new java.awt.Color(255, 255, 255));
        updateBirthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        updateBirthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBirthdayActionPerformed(evt);
            }
        });
        jPanel1.add(updateBirthday);
        updateBirthday.setBounds(280, 390, 180, 40);

        updateAdress.setBackground(new java.awt.Color(255, 255, 255));
        updateAdress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        updateAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAdressActionPerformed(evt);
            }
        });
        jPanel1.add(updateAdress);
        updateAdress.setBounds(720, 360, 180, 40);

        updateUser.setBackground(new java.awt.Color(255, 255, 255));
        updateUser.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        updateUser.setForeground(new java.awt.Color(0, 0, 0));
        updateUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "profesor", "empleado" }));
        updateUser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        updateUser.setMaximumSize(new java.awt.Dimension(0, 0));
        updateUser.setMinimumSize(new java.awt.Dimension(0, 0));
        updateUser.setPreferredSize(new java.awt.Dimension(0, 0));
        updateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserActionPerformed(evt);
            }
        });
        jPanel1.add(updateUser);
        updateUser.setBounds(280, 200, 175, 40);

        jLabel1.setBackground(new java.awt.Color(196, 196, 196));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("<html>Tipo de teléfono</html>");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel1.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 220, 190, 60);

        birthday.setBackground(new java.awt.Color(196, 196, 196));
        birthday.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        birthday.setForeground(new java.awt.Color(0, 0, 0));
        birthday.setText("<html>Fecha de nacimiento</html>");
        birthday.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        birthday.setMaximumSize(new java.awt.Dimension(0, 0));
        birthday.setMinimumSize(new java.awt.Dimension(0, 0));
        birthday.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(birthday);
        birthday.setBounds(40, 380, 186, 70);

        user.setBackground(new java.awt.Color(196, 196, 196));
        user.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        user.setForeground(new java.awt.Color(0, 0, 0));
        user.setText("<html>Tipo de usuario</html>");
        user.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        user.setMaximumSize(new java.awt.Dimension(0, 0));
        user.setMinimumSize(new java.awt.Dimension(0, 0));
        user.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(user);
        user.setBounds(40, 190, 186, 70);

        phoneType.setBackground(new java.awt.Color(196, 196, 196));
        phoneType.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        phoneType.setForeground(new java.awt.Color(0, 0, 0));
        phoneType.setText("<html>Telefono</html>");
        phoneType.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        phoneType.setMaximumSize(new java.awt.Dimension(0, 0));
        phoneType.setMinimumSize(new java.awt.Dimension(0, 0));
        phoneType.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(phoneType);
        phoneType.setBounds(500, 280, 186, 70);

        adress.setBackground(new java.awt.Color(196, 196, 196));
        adress.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        adress.setForeground(new java.awt.Color(0, 0, 0));
        adress.setText("<html>Dirección</html>");
        adress.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        adress.setMaximumSize(new java.awt.Dimension(0, 0));
        adress.setMinimumSize(new java.awt.Dimension(0, 0));
        adress.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(adress);
        adress.setBounds(500, 340, 186, 70);

        lastName.setBackground(new java.awt.Color(196, 196, 196));
        lastName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lastName.setForeground(new java.awt.Color(0, 0, 0));
        lastName.setText("<html>Apellido</html>");
        lastName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lastName.setMaximumSize(new java.awt.Dimension(0, 0));
        lastName.setMinimumSize(new java.awt.Dimension(0, 0));
        lastName.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(lastName);
        lastName.setBounds(40, 310, 186, 70);

        name.setBackground(new java.awt.Color(196, 196, 196));
        name.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        name.setForeground(new java.awt.Color(0, 0, 0));
        name.setText("<html>Nombre</html>");
        name.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        name.setMaximumSize(new java.awt.Dimension(0, 0));
        name.setMinimumSize(new java.awt.Dimension(0, 0));
        name.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(name);
        name.setBounds(40, 250, 186, 70);

        botonVolver.setBackground(new java.awt.Color(196, 196, 196));
        botonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close.png"))); // NOI18N
        botonVolver.setBorder(null);
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(botonVolver);
        botonVolver.setBounds(40, 50, 100, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updatePhoneTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePhoneTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePhoneTypeActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void updateLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateLastNameActionPerformed

    private void updateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateNameActionPerformed

    private void updatePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePhoneActionPerformed

    private void updateBirthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBirthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBirthdayActionPerformed

    private void updateAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateAdressActionPerformed

    private void updateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateUserActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adress;
    private javax.swing.JLabel birthday;
    public javax.swing.JButton botonActualizar;
    public javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phoneType;
    public javax.swing.JTextField updateAdress;
    public javax.swing.JTextField updateBirthday;
    public javax.swing.JTextField updateLastName;
    public javax.swing.JTextField updateName;
    public javax.swing.JTextField updatePhone;
    public javax.swing.JComboBox<String> updatePhoneType;
    public javax.swing.JComboBox<String> updateUser;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
