/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Juan
 */
public class ShowUsers extends javax.swing.JFrame {

    /**
     * Creates new form ShowUsers
     */
    public ShowUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        adress = new javax.swing.JLabel();
        numberPhone = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        showAdress = new javax.swing.JLabel();
        showUser = new javax.swing.JLabel();
        showName = new javax.swing.JLabel();
        showLastName = new javax.swing.JLabel();
        showBirthday = new javax.swing.JLabel();
        showPhone = new javax.swing.JLabel();
        showNumberPhone = new javax.swing.JLabel();
        botonMenuPrincipal = new javax.swing.JButton();
        jTextField17 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(196, 196, 196));
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 600));
        jPanel1.setLayout(null);

        title.setBackground(new java.awt.Color(196, 196, 196));
        title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Información del usuario");
        jPanel1.add(title);
        title.setBounds(290, 60, 410, 68);

        User.setBackground(new java.awt.Color(196, 196, 196));
        User.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        User.setForeground(new java.awt.Color(0, 0, 0));
        User.setText("<html>Tipo de usuario</html>");
        User.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        User.setMaximumSize(new java.awt.Dimension(0, 0));
        User.setMinimumSize(new java.awt.Dimension(0, 0));
        User.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(User);
        User.setBounds(90, 150, 186, 70);

        Name.setBackground(new java.awt.Color(196, 196, 196));
        Name.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Name.setForeground(new java.awt.Color(0, 0, 0));
        Name.setText("<html>Nombre</html>");
        Name.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Name.setMaximumSize(new java.awt.Dimension(0, 0));
        Name.setMinimumSize(new java.awt.Dimension(0, 0));
        Name.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(Name);
        Name.setBounds(90, 210, 186, 70);

        lastName.setBackground(new java.awt.Color(196, 196, 196));
        lastName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lastName.setForeground(new java.awt.Color(0, 0, 0));
        lastName.setText("<html>Apellido</html>");
        lastName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lastName.setMaximumSize(new java.awt.Dimension(0, 0));
        lastName.setMinimumSize(new java.awt.Dimension(0, 0));
        lastName.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(lastName);
        lastName.setBounds(90, 270, 186, 70);

        birthday.setBackground(new java.awt.Color(196, 196, 196));
        birthday.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        birthday.setForeground(new java.awt.Color(0, 0, 0));
        birthday.setText("<html>Fecha de nacimiento</html>");
        birthday.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        birthday.setMaximumSize(new java.awt.Dimension(0, 0));
        birthday.setMinimumSize(new java.awt.Dimension(0, 0));
        birthday.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(birthday);
        birthday.setBounds(90, 340, 186, 70);

        adress.setBackground(new java.awt.Color(196, 196, 196));
        adress.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        adress.setForeground(new java.awt.Color(0, 0, 0));
        adress.setText("<html>Dirección</html>");
        adress.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        adress.setMaximumSize(new java.awt.Dimension(0, 0));
        adress.setMinimumSize(new java.awt.Dimension(0, 0));
        adress.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(adress);
        adress.setBounds(500, 270, 186, 70);

        numberPhone.setBackground(new java.awt.Color(196, 196, 196));
        numberPhone.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        numberPhone.setForeground(new java.awt.Color(0, 0, 0));
        numberPhone.setText("<html>Telefono</html>");
        numberPhone.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        numberPhone.setMaximumSize(new java.awt.Dimension(0, 0));
        numberPhone.setMinimumSize(new java.awt.Dimension(0, 0));
        numberPhone.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(numberPhone);
        numberPhone.setBounds(500, 210, 186, 70);

        phone.setBackground(new java.awt.Color(196, 196, 196));
        phone.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        phone.setForeground(new java.awt.Color(0, 0, 0));
        phone.setText("<html>Tipo de teléfono</html>");
        phone.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        phone.setMaximumSize(new java.awt.Dimension(0, 0));
        phone.setMinimumSize(new java.awt.Dimension(0, 0));
        phone.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel1.add(phone);
        phone.setBounds(500, 150, 190, 60);

        showAdress.setBackground(new java.awt.Color(255, 255, 255));
        showAdress.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        showAdress.setForeground(new java.awt.Color(0, 0, 0));
        showAdress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showAdress.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(showAdress);
        showAdress.setBounds(710, 280, 170, 40);

        showUser.setBackground(new java.awt.Color(255, 255, 255));
        showUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        showUser.setForeground(new java.awt.Color(0, 0, 0));
        showUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showUser.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(showUser);
        showUser.setBounds(300, 160, 170, 40);

        showName.setBackground(new java.awt.Color(255, 255, 255));
        showName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        showName.setForeground(new java.awt.Color(0, 0, 0));
        showName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(showName);
        showName.setBounds(300, 220, 170, 40);

        showLastName.setBackground(new java.awt.Color(255, 255, 255));
        showLastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        showLastName.setForeground(new java.awt.Color(0, 0, 0));
        showLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showLastName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(showLastName);
        showLastName.setBounds(300, 280, 170, 40);

        showBirthday.setBackground(new java.awt.Color(255, 255, 255));
        showBirthday.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        showBirthday.setForeground(new java.awt.Color(0, 0, 0));
        showBirthday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showBirthday.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(showBirthday);
        showBirthday.setBounds(300, 350, 170, 40);

        showPhone.setBackground(new java.awt.Color(255, 255, 255));
        showPhone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        showPhone.setForeground(new java.awt.Color(0, 0, 0));
        showPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showPhone.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(showPhone);
        showPhone.setBounds(710, 160, 170, 40);

        showNumberPhone.setBackground(new java.awt.Color(255, 255, 255));
        showNumberPhone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        showNumberPhone.setForeground(new java.awt.Color(0, 0, 0));
        showNumberPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showNumberPhone.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        jPanel1.add(showNumberPhone);
        showNumberPhone.setBounds(710, 220, 170, 40);

        botonMenuPrincipal.setBackground(new java.awt.Color(131, 131, 131));
        botonMenuPrincipal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        botonMenuPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        botonMenuPrincipal.setText("Ok");
        botonMenuPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, java.awt.Color.black));
        botonMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuPrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(botonMenuPrincipal);
        botonMenuPrincipal.setBounds(400, 460, 170, 60);

        jTextField17.setBackground(new java.awt.Color(196, 196, 196));
        jTextField17.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(0, 0, 0));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("Developed by jviedman dev - enriquez dev");
        jTextField17.setBorder(null);
        jPanel1.add(jTextField17);
        jTextField17.setBounds(211, 540, 520, 19);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 0, 950, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel User;
    private javax.swing.JLabel adress;
    private javax.swing.JLabel birthday;
    public javax.swing.JButton botonMenuPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel numberPhone;
    private javax.swing.JLabel phone;
    public javax.swing.JLabel showAdress;
    public javax.swing.JLabel showBirthday;
    public javax.swing.JLabel showLastName;
    public javax.swing.JLabel showName;
    public javax.swing.JLabel showNumberPhone;
    public javax.swing.JLabel showPhone;
    public javax.swing.JLabel showUser;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
